/*****************************************************************************
 *                                                                           *
 *  Copyright 2018 Rice University                                           *
 *                                                                           *
 *  Licensed under the Apache License, Version 2.0 (the "License");          *
 *  you may not use this file except in compliance with the License.         *
 *  You may obtain a copy of the License at                                  *
 *                                                                           *
 *      http://www.apache.org/licenses/LICENSE-2.0                           *
 *                                                                           *
 *  Unless required by applicable law or agreed to in writing, software      *
 *  distributed under the License is distributed on an "AS IS" BASIS,        *
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 *  See the License for the specific language governing permissions and      *
 *  limitations under the License.                                           *
 *                                                                           *
 *****************************************************************************/
// Auto-generated by code in SConstruct
#define NoMsg_TYPEID 0
#define Employee_TYPEID 1
#define StorageTestSetScan_TYPEID 2
#define StorageGetData_TYPEID 3
#define Nothing_TYPEID 4
#define DispatcherAddData_TYPEID 5
#define CatCreateDatabaseRequest_TYPEID 6
#define Object_TYPEID 7
#define StoragePagePinned_TYPEID 8
#define BackendExecuteSelection_TYPEID 9
#define CatTypeSearchResult_TYPEID 10
#define CatTypeNameSearchResult_TYPEID 11
#define ExecuteQueryOnSingleHost_TYPEID 12
#define Ack_TYPEID 13
#define KeepGoing_TYPEID 14
#define StorageRemoveUserSet_TYPEID 15
#define StorageAddDatabase_TYPEID 16
#define ExecuteQueriesOnCluster_TYPEID 17
#define DoneWithResult_TYPEID 18
#define StorageTestSetCopy_TYPEID 19
#define ExecuteQuery_TYPEID 20
#define GetListOfNodes_TYPEID 21
#define SetScan_TYPEID 22
#define QueryDone_TYPEID 23
#define StorageNoMorePage_TYPEID 24
#define CatSharedLibraryResult_TYPEID 25
#define RequestResources_TYPEID 26
#define PlaceOfQueryPlanner_TYPEID 27
#define StorageAddTempSet_TYPEID 28
#define StorageGetDataResponse_TYPEID 29
#define Handle_TYPEID 30
#define StorageAddSet_TYPEID 31
#define StorageUnpinPage_TYPEID 32
#define Company_TYPEID 33
#define CloseConnection_TYPEID 34
#define CatSetObjectTypeRequest_TYPEID 35
#define ListOfNodes_TYPEID 36
#define Map_TYPEID 37
#define MyEmployee_TYPEID 38
#define String_TYPEID 39
#define Vector_TYPEID 40
#define BackendTestSetScan_TYPEID 41
#define ShutDown_TYPEID 42
#define DispatcherRegisterPartitionPolicy_TYPEID 43
#define StorageAddType_TYPEID 44
#define CheckEmployee_TYPEID 45
#define PairArray_TYPEID 46
#define Supervisor_TYPEID 47
#define QueryPermitResponse_TYPEID 48
#define CatSharedLibraryRequest_TYPEID 49
#define StorageAddTempSetResult_TYPEID 50
#define CatCreateSetRequest_TYPEID 51
#define NodeDispatcherData_TYPEID 52
#define QueryOutput_TYPEID 53
#define StorageGetSetPages_TYPEID 54
#define QueryPermit_TYPEID 55
#define StoragePinPage_TYPEID 56
#define BackendTestSetCopy_TYPEID 57
#define DeleteSet_TYPEID 58
#define StorageAddData_TYPEID 59
#define StorageRemoveTempSet_TYPEID 60
#define Set_TYPEID 61
#define CatTypeNameSearch_TYPEID 62
#define NodeInfo_TYPEID 63
#define SimpleRequestResult_TYPEID 64
#define CatRegisterType_TYPEID 65
#define Array_TYPEID 66
