/*****************************************************************************
 *                                                                           *
 *  Copyright 2018 Rice University                                           *
 *                                                                           *
 *  Licensed under the Apache License, Version 2.0 (the "License");          *
 *  you may not use this file except in compliance with the License.         *
 *  You may obtain a copy of the License at                                  *
 *                                                                           *
 *      http://www.apache.org/licenses/LICENSE-2.0                           *
 *                                                                           *
 *  Unless required by applicable law or agreed to in writing, software      *
 *  distributed under the License is distributed on an "AS IS" BASIS,        *
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 *  See the License for the specific language governing permissions and      *
 *  limitations under the License.                                           *
 *                                                                           *
 *****************************************************************************/
// Auto-generated by code in SConstruct
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/Array.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CatCreateDatabaseRequest.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CatCreateSetRequest.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CatRegisterType.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CatSetObjectTypeRequest.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CatSharedLibraryRequest.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CatSharedLibraryResult.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CatTypeNameSearch.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CatTypeNameSearchResult.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CatTypeSearchResult.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CheckEmployees.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/CloseConnection.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/Company.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/Employee.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/Nothing.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/PDBHandlePrototype.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/PDBObjectPrototype.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/PDBString.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/PDBVector.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/ShutDown.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/SimpleRequestResult.h"
#include "/Users/christopherjermaine/ObjectQueryModel/src/builtInPDBObjects/headers/Supervisor.h"
