/*****************************************************************************
 *                                                                           *
 *  Copyright 2018 Rice University                                           *
 *                                                                           *
 *  Licensed under the Apache License, Version 2.0 (the "License");          *
 *  you may not use this file except in compliance with the License.         *
 *  You may obtain a copy of the License at                                  *
 *                                                                           *
 *      http://www.apache.org/licenses/LICENSE-2.0                           *
 *                                                                           *
 *  Unless required by applicable law or agreed to in writing, software      *
 *  distributed under the License is distributed on an "AS IS" BASIS,        *
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 *  See the License for the specific language governing permissions and      *
 *  limitations under the License.                                           *
 *                                                                           *
 *****************************************************************************/
// Auto-generated by code in SConstruct
#define NoMsg_TYPEID 0
#define QueryPermit_TYPEID 1
#define StorageAddSet_TYPEID 2
#define Array_TYPEID 3
#define Ack_TYPEID 4
#define Nothing_TYPEID 5
#define KeepGoing_TYPEID 6
#define Employee_TYPEID 7
#define Handle_TYPEID 8
#define Company_TYPEID 9
#define NodeInfo_TYPEID 10
#define StorageAddTempSet_TYPEID 11
#define DoneWithResult_TYPEID 12
#define CatTypeNameSearchResult_TYPEID 13
#define CatTypeSearchResult_TYPEID 14
#define ExecuteQuery_TYPEID 15
#define PlaceOfQueryPlanner_TYPEID 16
#define QueryPermitResponse_TYPEID 17
#define QueryDone_TYPEID 18
#define CheckEmployee_TYPEID 19
#define ShutDown_TYPEID 20
#define Supervisor_TYPEID 21
#define StorageGetSetPages_TYPEID 22
#define CatCreateSetRequest_TYPEID 23
#define CatSetObjectTypeRequest_TYPEID 24
#define StorageRemoveTempSet_TYPEID 25
#define SetScan_TYPEID 26
#define Vector_TYPEID 27
#define CatSharedLibraryResult_TYPEID 28
#define Object_TYPEID 29
#define StorageGetData_TYPEID 30
#define StorageGetDataResponse_TYPEID 31
#define CatTypeNameSearch_TYPEID 32
#define StoragePagePinned_TYPEID 33
#define String_TYPEID 34
#define CatSharedLibraryRequest_TYPEID 35
#define StorageAddType_TYPEID 36
#define StoragePinPage_TYPEID 37
#define CatCreateDatabaseRequest_TYPEID 38
#define SimpleRequestResult_TYPEID 39
#define CatRegisterType_TYPEID 40
#define StorageAddDatabase_TYPEID 41
#define StorageUnpinPage_TYPEID 42
#define StorageNoMorePage_TYPEID 43
#define StorageAddData_TYPEID 44
#define MyEmployee_TYPEID 45
#define CloseConnection_TYPEID 46
