/*****************************************************************************
 *                                                                           *
 *  Copyright 2018 Rice University                                           *
 *                                                                           *
 *  Licensed under the Apache License, Version 2.0 (the "License");          *
 *  you may not use this file except in compliance with the License.         *
 *  You may obtain a copy of the License at                                  *
 *                                                                           *
 *      http://www.apache.org/licenses/LICENSE-2.0                           *
 *                                                                           *
 *  Unless required by applicable law or agreed to in writing, software      *
 *  distributed under the License is distributed on an "AS IS" BASIS,        *
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 *  See the License for the specific language governing permissions and      *
 *  limitations under the License.                                           *
 *                                                                           *
 *****************************************************************************/
// Auto-generated by code in SConstruct
#define NoMsg_TYPEID 0
#define Array_TYPEID 1
#define CatCreateDatabaseRequest_TYPEID 2
#define CatCreateSetRequest_TYPEID 3
#define CatRegisterType_TYPEID 4
#define CatSetObjectTypeRequest_TYPEID 5
#define CatSharedLibraryRequest_TYPEID 6
#define CatSharedLibraryResult_TYPEID 7
#define CatTypeNameSearch_TYPEID 8
#define CatTypeNameSearchResult_TYPEID 9
#define CatTypeSearchResult_TYPEID 10
#define CheckEmployee_TYPEID 11
#define CloseConnection_TYPEID 12
#define Company_TYPEID 13
#define Employee_TYPEID 14
#define Nothing_TYPEID 15
#define Handle_TYPEID 16
#define Object_TYPEID 17
#define String_TYPEID 18
#define Vector_TYPEID 19
#define ShutDown_TYPEID 20
#define SimpleRequestResult_TYPEID 21
#define Supervisor_TYPEID 22
